GET http://localhost:3000/api/fruits

###

GET http://localhost:3000/api/fruits/1

###

POST http://localhost:3000/api/fruits
content-type: application/json

{
    "fruit": "strawberry"
}

###

DELETE http://localhost:3000/api/fruits/1

###

DELETE http://localhost:3000/api/fruits/